server:
  port: 8440

spring:
  activemq:
    broker-url: tcp://localhost:61616
    username: admin
    password: admin
  queues:
    durability:
      queue: simple-queue
      topic: simple-topic
    sync-communication:
      request-queue: sync.requestQueue
      reply-queue: sync.replyQueue